### ISSUE TITLE
there is no How To connect with amazon credentials

### ISSUE THREAD

**Issue by fbrau** [Miserlou/NoDB#6]
there is no documentation about how to pass amazon credentials

My first attent went: "The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256".

What next?

**Comment by Miserlou** [comment]
How are you storing your AWS credentials? I think I have been assuming that you've got something set up in your `~/.aws/credentials`..

**Comment by fbrau** [comment]
I have this (keys replaced with ***)

>> cat .aws/credentials 
[default]
aws_access_key_id = *******
aws_secret_access_key =  *********

and I still get that message

**Comment by Miserlou** [comment]
What region is your bucket in? Probably related to this: http://stackoverflow.com/a/26538266

**Comment by bendog** [comment]
#20 should fix this
