### ISSUE TITLE
Authorization problem for fresh AWS regions

### ISSUE THREAD

**Issue by koriaf** [Miserlou/NoDB#7]
us-default supports both v2 and v4 auth, but Frankfurt for example doesn't support v2 (used by default).
So instead of:
```
s3 = boto3.resource('s3')
```
It shall be
```
boto3.resource('s3', config=botocore.client.Config(signature_version='s3v4'))
```
(or please document some global way to do it).

**Comment by szilagyiabo** [comment]
This PL fixes it: #10

In version 0.2.2 you can change signature version by defining _nodb.signature_version_ property (default:  's3v4').

**Comment by Miserlou** [comment]
👍

**Comment by Miserlou** [comment]
Wait, does this work everywhere now? Or _only_ for the new ones? Zappa has some region-specific code for this, I think..

**Comment by szilagyiabo** [comment]
Amazon claims that _"Amazon S3 now supports the latest Signature Version 4, which is supported in all regions; it is the only version supported for new AWS regions."_ [link](http://docs.aws.amazon.com/AmazonS3/latest/dev/auth-request-sig-v2.html)

I did not test it for all regions, but i think it's going to work for all.

If a new signature version will pop up in the future, you can use the _nodb.signature_version_ property.
